import 'dart:math';
import 'package:latlong2/latlong.dart';
import 'package:sua_vaga/models/parking_model.dart';
import 'package:sua_vaga/models/spot_model.dart';
import 'package:sua_vaga/repositories/json_converter.dart';
import 'package:sua_vaga/repositories/parking_repository.dart';

Future<void> insertParkingLot() async {
  final repository = ParkingRepository();

  final newParkingLot = ParkingLot(
    id: '5',
    name: 'teste1',
    location: const LatLng(-22.86201342289818, -46.97658106761099),
    adress: 'rua teste1',
    layout: _parkingLayout(),
  );

  await repository.addParkingLot(newParkingLot);
}

//atualização de vagas (posição e dados)

Future<void> updateSpots() async {
  final repository = ParkingRepository();
  final random = Random();
  //final types = ['carro', 'moto', 'deficiente'];

  Map<String, dynamic> updates = {};

  const int spotsPerRow = 16;
  const List<String> prefixes = ['I', 'J'];
  //row pode funcionar como column, é apenas um nome genérico
  for (int row = 0; row < prefixes.length; row++) {
    final prefix = prefixes[row];
    for (int i = 0; i < spotsPerRow; i++) {
      final int spotNumber = i + 1;
      final String spotId = '$prefix$spotNumber';
      final double x = 100.0 + (i * 50);
      //se quiser q os spots saiam em coluna colocar i no y, senão coloque no x
      final double y = 900.0 + (row * 150);
      final spot = Spot(
        id: spotId,
        status: random.nextBool(),
        type: 'carro',
        x: x,
        y: y,
        width: 50.0,
        height: 75.0,
      );
      //criando uma lista de map String dynamic e add todos de uma vez, pega o cahve q é o colchetes e bota como valor o spot.toMap
      updates['floors.0.layout.spots.$spotId'] = spot.toMap();
    }
  }

  await repository.updateParking('1', updates);
}

//atualização e criação de elementos do layout

Future<void> updateElement() async {
  final repository = ParkingRepository();
  //tipos: join, leave, arrow, text
  //somente join, leave e text aceita um text
  final element = LayoutElement(
    type: 'leave',
    x: 950.0,
    y: 10.0,
    size: 40.0,
    label: 'Saída',
  );
  //Não esqueça de mudar o ID aqui
  await repository.updateParking('1', {
    'floors.0.layout.elements.leave': element.toMap(),
  });
}

Future<void> updateMultipleArrows() async {
  final repository = ParkingRepository();

  Map<String, dynamic> updates = {};

  //quantidade de elementos a ser criado
  int elementsNumber = 5;

  //numero da primeira seta q vai alterar, vai incrementar de 1 em 1 dai
  int nameCount = 1;

  for (int i = 0; i < elementsNumber; i++) {
    //colocar i * no x caso esteja tratando de colunas no y é quando tem linhas
    final double x = 485.0; //+ (i * 275);
    final double y = 75.0 + (i * 225);
    final String name = 'arrow$nameCount';
    final element = LayoutElement(type: 'arrow', x: x, y: y, rotation: 0);
    updates['floors.0.layout.elements.$name'] = element.toMap();
    nameCount++;
  }

  await repository.updateParking('1', updates);
}

Future<void> update() async {
  final repository = ParkingRepository();

  await repository.updateParking('1', {'floors.0.layout.height': 1125});
}

//funções de geração

ParkingLayout _parkingLayout() {
  return ParkingLayout(
    width: 1000.0,
    height: 1000.0,
    elements: generateLayoutElements(),
    spots: _generateSpots(),
  );
}

Map<String, Spot> _generateSpots() {
  final random = Random();
  final types = ['carro', 'moto', 'deficiente'];

  return Map.fromEntries(
    List.generate(3, (i) {
      final id = 'A${i + 1}';
      final spot = Spot(
        id: id,
        status: random.nextBool(),
        type: types[random.nextInt(types.length)],
        x: 100.0 + (i * 50),
        y: 100.0,
        width: 50,
        height: 80,
        rotation: null,
      );
      return MapEntry(id, spot);
    }),
  );
}

Map<String, LayoutElement> generateLayoutElements() {
  return {
    'arrow1': LayoutElement(type: 'arrow', x: 50.0, y: 20.0, rotation: 0),
    'arrow2': LayoutElement(type: 'arrow', x: 900.0, y: 950.0, rotation: 180),
  };
}

Future<void> insertSpecificParkingLot() async {
  final repository = ParkingRepository();
  final lotCentroMedico = parkingLotFromJson({
    "adress":
        "R. Dr. Edilberto Luís Pereira da Silva, 929 - Cidade Universitária, Campinas - SP, 13083-190",
    "id": "6",
    "layout": {
      "elements": {
        "arrow1": {
          "fontSize": 40,
          "rotation": 90,
          "type": "arrow",
          "x": 180,
          "y": 650,
        },
        "arrow10": {
          "fontSize": 40,
          "rotation": 0,
          "type": "arrow",
          "x": 630,
          "y": 50,
        },
        "arrow11": {
          "fontSize": 40,
          "rotation": 0,
          "type": "arrow",
          "x": 630,
          "y": 1305,
        },
        "arrow12": {
          "fontSize": 40,
          "rotation": 180,
          "type": "arrow",
          "x": 630,
          "y": 1355,
        },
        "arrow2": {
          "fontSize": 40,
          "rotation": 90,
          "type": "arrow",
          "x": 455,
          "y": 650,
        },
        "arrow3": {
          "fontSize": 40,
          "rotation": 90,
          "type": "arrow",
          "x": 730,
          "y": 650,
        },
        "arrow4": {
          "fontSize": 40,
          "rotation": 90,
          "type": "arrow",
          "x": 1005,
          "y": 650,
        },
        "arrow5": {
          "fontSize": 40,
          "rotation": 270,
          "type": "arrow",
          "x": 250,
          "y": 650,
        },
        "arrow6": {
          "fontSize": 40,
          "rotation": 270,
          "type": "arrow",
          "x": 525,
          "y": 650,
        },
        "arrow7": {
          "fontSize": 40,
          "rotation": 270,
          "type": "arrow",
          "x": 800,
          "y": 650,
        },
        "arrow8": {
          "fontSize": 40,
          "rotation": 270,
          "type": "arrow",
          "x": 1075,
          "y": 650,
        },
        "arrow9": {
          "fontSize": 40,
          "rotation": 180,
          "type": "arrow",
          "x": 630,
          "y": 0,
        },
        "entrada": {
          "fontSize": 70,
          "label": "Entrada e Saída",
          "type": "join",
          "x": 1100,
          "y": 10,
        },
      },
      "height": 1400,
      "spots": {
        "A1": {
          "height": 50,
          "id": "A1",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 350,
        },
        "A10": {
          "height": 50,
          "id": "A10",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 800,
        },
        "A11": {
          "height": 50,
          "id": "A11",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 850,
        },
        "A12": {
          "height": 50,
          "id": "A12",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 900,
        },
        "A13": {
          "height": 50,
          "id": "A13",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 950,
        },
        "A14": {
          "height": 50,
          "id": "A14",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 1000,
        },
        "A15": {
          "height": 50,
          "id": "A15",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 1050,
        },
        "A16": {
          "height": 50,
          "id": "A16",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 1100,
        },
        "A17": {
          "height": 50,
          "id": "A17",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 1150,
        },
        "A18": {
          "height": 50,
          "id": "A18",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 1200,
        },
        "A19": {
          "height": 50,
          "id": "A19",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 1250,
        },
        "A2": {
          "height": 50,
          "id": "A2",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 400,
        },
        "A3": {
          "height": 50,
          "id": "A3",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 450,
        },
        "A4": {
          "height": 50,
          "id": "A4",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 500,
        },
        "A5": {
          "height": 50,
          "id": "A5",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 550,
        },
        "A6": {
          "height": 50,
          "id": "A6",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 600,
        },
        "A7": {
          "height": 50,
          "id": "A7",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 650,
        },
        "A8": {
          "height": 50,
          "id": "A8",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 700,
        },
        "A9": {
          "height": 50,
          "id": "A9",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 100,
          "y": 750,
        },
        "B1": {
          "height": 50,
          "id": "B1",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 100,
        },
        "B10": {
          "height": 50,
          "id": "B10",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 550,
        },
        "B11": {
          "height": 50,
          "id": "B11",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 600,
        },
        "B12": {
          "height": 50,
          "id": "B12",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 650,
        },
        "B13": {
          "height": 50,
          "id": "B13",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 700,
        },
        "B14": {
          "height": 50,
          "id": "B14",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 750,
        },
        "B15": {
          "height": 50,
          "id": "B15",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 800,
        },
        "B16": {
          "height": 50,
          "id": "B16",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 850,
        },
        "B17": {
          "height": 50,
          "id": "B17",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 900,
        },
        "B18": {
          "height": 50,
          "id": "B18",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 950,
        },
        "B19": {
          "height": 50,
          "id": "B19",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 1000,
        },
        "B2": {
          "height": 50,
          "id": "B2",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 150,
        },
        "B20": {
          "height": 50,
          "id": "B20",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 1050,
        },
        "B21": {
          "height": 50,
          "id": "B21",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 1100,
        },
        "B22": {
          "height": 50,
          "id": "B22",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 1150,
        },
        "B23": {
          "height": 50,
          "id": "B23",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 1200,
        },
        "B24": {
          "height": 50,
          "id": "B24",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 1250,
        },
        "B3": {
          "height": 50,
          "id": "B3",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 200,
        },
        "B4": {
          "height": 50,
          "id": "B4",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 250,
        },
        "B5": {
          "height": 50,
          "id": "B5",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 300,
        },
        "B6": {
          "height": 50,
          "id": "B6",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 350,
        },
        "B7": {
          "height": 50,
          "id": "B7",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 400,
        },
        "B8": {
          "height": 50,
          "id": "B8",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 450,
        },
        "B9": {
          "height": 50,
          "id": "B9",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 300,
          "y": 500,
        },
        "C1": {
          "height": 50,
          "id": "C1",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 100,
        },
        "C10": {
          "height": 50,
          "id": "C10",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 550,
        },
        "C11": {
          "height": 50,
          "id": "C11",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 600,
        },
        "C12": {
          "height": 50,
          "id": "C12",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 650,
        },
        "C13": {
          "height": 50,
          "id": "C13",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 700,
        },
        "C14": {
          "height": 50,
          "id": "C14",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 750,
        },
        "C15": {
          "height": 50,
          "id": "C15",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 800,
        },
        "C16": {
          "height": 50,
          "id": "C16",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 850,
        },
        "C17": {
          "height": 50,
          "id": "C17",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 900,
        },
        "C18": {
          "height": 50,
          "id": "C18",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 950,
        },
        "C19": {
          "height": 50,
          "id": "C19",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 1000,
        },
        "C2": {
          "height": 50,
          "id": "C2",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 150,
        },
        "C20": {
          "height": 50,
          "id": "C20",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 1050,
        },
        "C21": {
          "height": 50,
          "id": "C21",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 1100,
        },
        "C22": {
          "height": 50,
          "id": "C22",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 1150,
        },
        "C23": {
          "height": 50,
          "id": "C23",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 1200,
        },
        "C24": {
          "height": 50,
          "id": "C24",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 1250,
        },
        "C3": {
          "height": 50,
          "id": "C3",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 200,
        },
        "C4": {
          "height": 50,
          "id": "C4",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 250,
        },
        "C5": {
          "height": 50,
          "id": "C5",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 300,
        },
        "C6": {
          "height": 50,
          "id": "C6",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 350,
        },
        "C7": {
          "height": 50,
          "id": "C7",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 400,
        },
        "C8": {
          "height": 50,
          "id": "C8",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 450,
        },
        "C9": {
          "height": 50,
          "id": "C9",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 375,
          "y": 500,
        },
        "D1": {
          "height": 50,
          "id": "D1",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 100,
        },
        "D10": {
          "height": 50,
          "id": "D10",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 550,
        },
        "D11": {
          "height": 50,
          "id": "D11",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 600,
        },
        "D12": {
          "height": 50,
          "id": "D12",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 650,
        },
        "D13": {
          "height": 50,
          "id": "D13",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 700,
        },
        "D14": {
          "height": 50,
          "id": "D14",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 750,
        },
        "D15": {
          "height": 50,
          "id": "D15",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 800,
        },
        "D16": {
          "height": 50,
          "id": "D16",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 850,
        },
        "D17": {
          "height": 50,
          "id": "D17",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 900,
        },
        "D18": {
          "height": 50,
          "id": "D18",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 950,
        },
        "D19": {
          "height": 50,
          "id": "D19",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 1000,
        },
        "D2": {
          "height": 50,
          "id": "D2",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 150,
        },
        "D20": {
          "height": 50,
          "id": "D20",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 1050,
        },
        "D21": {
          "height": 50,
          "id": "D21",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 1100,
        },
        "D22": {
          "height": 50,
          "id": "D22",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 1150,
        },
        "D23": {
          "height": 50,
          "id": "D23",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 1200,
        },
        "D24": {
          "height": 50,
          "id": "D24",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 1250,
        },
        "D3": {
          "height": 50,
          "id": "D3",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 200,
        },
        "D4": {
          "height": 50,
          "id": "D4",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 250,
        },
        "D5": {
          "height": 50,
          "id": "D5",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 300,
        },
        "D6": {
          "height": 50,
          "id": "D6",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 350,
        },
        "D7": {
          "height": 50,
          "id": "D7",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 400,
        },
        "D8": {
          "height": 50,
          "id": "D8",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 450,
        },
        "D9": {
          "height": 50,
          "id": "D9",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 575,
          "y": 500,
        },
        "E1": {
          "height": 50,
          "id": "E1",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 100,
        },
        "E10": {
          "height": 50,
          "id": "E10",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 550,
        },
        "E11": {
          "height": 50,
          "id": "E11",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 600,
        },
        "E12": {
          "height": 50,
          "id": "E12",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 650,
        },
        "E13": {
          "height": 50,
          "id": "E13",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 700,
        },
        "E14": {
          "height": 50,
          "id": "E14",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 750,
        },
        "E15": {
          "height": 50,
          "id": "E15",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 800,
        },
        "E16": {
          "height": 50,
          "id": "E16",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 850,
        },
        "E17": {
          "height": 50,
          "id": "E17",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 900,
        },
        "E18": {
          "height": 50,
          "id": "E18",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 950,
        },
        "E19": {
          "height": 50,
          "id": "E19",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 1000,
        },
        "E2": {
          "height": 50,
          "id": "E2",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 150,
        },
        "E20": {
          "height": 50,
          "id": "E20",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 1050,
        },
        "E21": {
          "height": 50,
          "id": "E21",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 1100,
        },
        "E22": {
          "height": 50,
          "id": "E22",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 1150,
        },
        "E23": {
          "height": 50,
          "id": "E23",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 1200,
        },
        "E24": {
          "height": 50,
          "id": "E24",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 1250,
        },
        "E3": {
          "height": 50,
          "id": "E3",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 200,
        },
        "E4": {
          "height": 50,
          "id": "E4",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 250,
        },
        "E5": {
          "height": 50,
          "id": "E5",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 300,
        },
        "E6": {
          "height": 50,
          "id": "E6",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 350,
        },
        "E7": {
          "height": 50,
          "id": "E7",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 400,
        },
        "E8": {
          "height": 50,
          "id": "E8",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 450,
        },
        "E9": {
          "height": 50,
          "id": "E9",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 650,
          "y": 500,
        },
        "F1": {
          "height": 50,
          "id": "F1",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 100,
        },
        "F10": {
          "height": 50,
          "id": "F10",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 550,
        },
        "F11": {
          "height": 50,
          "id": "F11",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 600,
        },
        "F12": {
          "height": 50,
          "id": "F12",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 650,
        },
        "F13": {
          "height": 50,
          "id": "F13",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 700,
        },
        "F14": {
          "height": 50,
          "id": "F14",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 750,
        },
        "F15": {
          "height": 50,
          "id": "F15",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 800,
        },
        "F16": {
          "height": 50,
          "id": "F16",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 850,
        },
        "F17": {
          "height": 50,
          "id": "F17",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 900,
        },
        "F18": {
          "height": 50,
          "id": "F18",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 950,
        },
        "F19": {
          "height": 50,
          "id": "F19",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 1000,
        },
        "F2": {
          "height": 50,
          "id": "F2",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 150,
        },
        "F20": {
          "height": 50,
          "id": "F20",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 1050,
        },
        "F21": {
          "height": 50,
          "id": "F21",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 1100,
        },
        "F22": {
          "height": 50,
          "id": "F22",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 1150,
        },
        "F23": {
          "height": 50,
          "id": "F23",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 1200,
        },
        "F24": {
          "height": 50,
          "id": "F24",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 1250,
        },
        "F3": {
          "height": 50,
          "id": "F3",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 200,
        },
        "F4": {
          "height": 50,
          "id": "F4",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 250,
        },
        "F5": {
          "height": 50,
          "id": "F5",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 300,
        },
        "F6": {
          "height": 50,
          "id": "F6",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 350,
        },
        "F7": {
          "height": 50,
          "id": "F7",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 400,
        },
        "F8": {
          "height": 50,
          "id": "F8",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 450,
        },
        "F9": {
          "height": 50,
          "id": "F9",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 850,
          "y": 500,
        },
        "G1": {
          "height": 50,
          "id": "G1",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 100,
        },
        "G10": {
          "height": 50,
          "id": "G10",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 550,
        },
        "G11": {
          "height": 50,
          "id": "G11",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 600,
        },
        "G12": {
          "height": 50,
          "id": "G12",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 650,
        },
        "G13": {
          "height": 50,
          "id": "G13",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 700,
        },
        "G14": {
          "height": 50,
          "id": "G14",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 750,
        },
        "G15": {
          "height": 50,
          "id": "G15",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 800,
        },
        "G16": {
          "height": 50,
          "id": "G16",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 850,
        },
        "G17": {
          "height": 50,
          "id": "G17",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 900,
        },
        "G18": {
          "height": 50,
          "id": "G18",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 950,
        },
        "G19": {
          "height": 50,
          "id": "G19",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 1000,
        },
        "G2": {
          "height": 50,
          "id": "G2",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 150,
        },
        "G20": {
          "height": 50,
          "id": "G20",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 1050,
        },
        "G21": {
          "height": 50,
          "id": "G21",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 1100,
        },
        "G22": {
          "height": 50,
          "id": "G22",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 1150,
        },
        "G23": {
          "height": 50,
          "id": "G23",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 1200,
        },
        "G24": {
          "height": 50,
          "id": "G24",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 1250,
        },
        "G3": {
          "height": 50,
          "id": "G3",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 200,
        },
        "G4": {
          "height": 50,
          "id": "G4",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 250,
        },
        "G5": {
          "height": 50,
          "id": "G5",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 300,
        },
        "G6": {
          "height": 50,
          "id": "G6",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 350,
        },
        "G7": {
          "height": 50,
          "id": "G7",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 400,
        },
        "G8": {
          "height": 50,
          "id": "G8",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 450,
        },
        "G9": {
          "height": 50,
          "id": "G9",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 925,
          "y": 500,
        },
        "H1": {
          "height": 50,
          "id": "H1",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 500,
        },
        "H10": {
          "height": 50,
          "id": "H10",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 950,
        },
        "H11": {
          "height": 50,
          "id": "H11",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 1000,
        },
        "H12": {
          "height": 50,
          "id": "H12",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 1050,
        },
        "H13": {
          "height": 50,
          "id": "H13",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 1100,
        },
        "H14": {
          "height": 50,
          "id": "H14",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 1150,
        },
        "H15": {
          "height": 50,
          "id": "H15",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 1200,
        },
        "H16": {
          "height": 50,
          "id": "H16",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 1250,
        },
        "H2": {
          "height": 50,
          "id": "H2",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 550,
        },
        "H3": {
          "height": 50,
          "id": "H3",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 600,
        },
        "H4": {
          "height": 50,
          "id": "H4",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 650,
        },
        "H5": {
          "height": 50,
          "id": "H5",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 700,
        },
        "H6": {
          "height": 50,
          "id": "H6",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 750,
        },
        "H7": {
          "height": 50,
          "id": "H7",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 800,
        },
        "H8": {
          "height": 50,
          "id": "H8",
          "status": false,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 850,
        },
        "H9": {
          "height": 50,
          "id": "H9",
          "status": true,
          "type": "carro",
          "width": 75,
          "x": 1125,
          "y": 900,
        },
      },
      "width": 1300,
    },
    "location": {"lat": -22.80787, "lng": -47.06501},
    "name": "Centro Médico de Campinas",
  });

  await repository.addParkingLot(lotCentroMedico);
}
