// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCToOciYYtUcxoXr5dAoG8YHhkzWA_QMIU',
    appId: '1:410875608459:web:51fb3eef4f65d7124b838e',
    messagingSenderId: '410875608459',
    projectId: 'sua-vaga-8e99e',
    authDomain: 'sua-vaga-8e99e.firebaseapp.com',
    storageBucket: 'sua-vaga-8e99e.firebasestorage.app',
    measurementId: 'G-GYJ15RT3ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrf9T1DPBQpXv16LCn1pz63z7M_NXH1-Y',
    appId: '1:410875608459:android:c5deb6e84b1f408a4b838e',
    messagingSenderId: '410875608459',
    projectId: 'sua-vaga-8e99e',
    storageBucket: 'sua-vaga-8e99e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRPHsfgG-_SoJt5D0GnnEKBbuNPfxei4',
    appId: '1:410875608459:ios:c4f0f0e0956a29824b838e',
    messagingSenderId: '410875608459',
    projectId: 'sua-vaga-8e99e',
    storageBucket: 'sua-vaga-8e99e.firebasestorage.app',
    iosBundleId: 'com.example.suaVaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRPHsfgG-_SoJt5D0GnnEKBbuNPfxei4',
    appId: '1:410875608459:ios:c4f0f0e0956a29824b838e',
    messagingSenderId: '410875608459',
    projectId: 'sua-vaga-8e99e',
    storageBucket: 'sua-vaga-8e99e.firebasestorage.app',
    iosBundleId: 'com.example.suaVaga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCToOciYYtUcxoXr5dAoG8YHhkzWA_QMIU',
    appId: '1:410875608459:web:da6389390d9a39554b838e',
    messagingSenderId: '410875608459',
    projectId: 'sua-vaga-8e99e',
    authDomain: 'sua-vaga-8e99e.firebaseapp.com',
    storageBucket: 'sua-vaga-8e99e.firebasestorage.app',
    measurementId: 'G-BECLR6YG6S',
  );
}
